rootProject.name = "Tasky"
include(":app")

include(":core:core")
include(":core:core-ui")
include(":core:design-system")
include(":core:agenda-manger")
include(":core:database-manager")
include(":core:navigation")
include(":core:preferences-manager")
include(":core:alarm-manager")
include(":core:notification-manager")
include(":core:permission-manager")

include(":feature:authentication")
include(":feature:home")
include(":feature:agenda:event")
include(":feature:agenda:reminder")
include(":feature:agenda:task")
include(":feature:splash")
