name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Lint Check
        run: ./gradlew lint
      - name: Upload Lint Report
        uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: app/build/reports/lint-results-debug.html
